* Introduction
The blockchain technology first gained its popularity as a decentralised ledger focusing on the exchange of asset or cryptocurrency like Bitcoin. Initially, this design provides solution to the problem of double-spending in digital money without the need of third-party entity like banks. Every transaction in blockchain is publicly recorded in a way that they cannot be changed (tamper-proof) using cryptography. This ensures trust between the participants in the network eventhough they do not know each other personally.

Today, blockchains have evolved from simply exchanging currency to becoming a general-purpose platform with the introduction of Ethereum and smart contracts. For this reason, it became programmable that eventually led its use in different sectors like in supply chain, healthcare, voting, and Internet of Things (IoT). At this point, blockchain is no longer about financial transaction; it has become a means of safe storage and sharing of information that depends on the needs of individual industries.

This growth in its capabilities led to an array of independent blockchain platforms that together contributed to the problem of interoperability. Despite their growth both in their capabilities and number, blockchains have not yet been widely adopted or succesfully integrated into today's mainstream technological systems. To address this, they need not only solutions to issues of decentralisation, scalability, and security (the blockchain trilemma), but also their capability to communicate with each other. Without interoperability, they will continue to remain only as information silos or disconnected islands of information that cannot exchange value and data directly. This limits the real potential of blockchain technology.

Solutions to interoperability exist like cross-chain bridges, relays, and sidechains. In recent literature, blockchain interoperability (BI) is divided into two aspects: digital asset interoperability (for cryptocurrency) and arbitrary data interoperability (for general information). This difference has been used by recent papers in order to understand the different logic and mechanisms needed by each category. Because of this, the issue of semantic interoperability surfaces. It is the challenge on how the meaning and correct interpretation of data remain consistent while they are being transferred to different blockchain networks.

The different protocols of BI also reflects the developmental evolution of blockchains. Earlier protocols were designed to facilitate transfer of assets from one blockchain network to another. Meanwhile, recent developments of protocols move towards the exchange of arbitrary data.  

This research focuses semantic comparative analysis between asset-based and data-based interoperability protocols using Process Algebra. Despite the growing number of technical solutions, there is still an insufficient number of formal understanding of their observable behaviours.  

** Problem Statement

 How do asset-based and a data-based blockchain  interoperability compare in terms of their semantically defined observable behaviour? Specifically, this research aims to answer the following
research questions:

1. How can asset-based and data-based blockchain interoperability protocols be formally defined?

2. What observable behaviours emerge form the semantic models?

3. In what ways do these obsservabe behaviours differ or align under a semantic framework?

   # blockchain interoperability focused on crypto, but there is an
increasing need for data interop, so we find out the semantic of these
crypto based interop, and the semantic of data- based interop, and
then find their differences.

** Objectives


*** Main Objective

*** Specific Objectives


** Scope and Limitations

# we use Wanchain and AppXChain interoperability protocols

This research focuses on the underlying logical properties rather than
the implementation details or empirical performance of certain
blockchain protocols.
*** Scope

*** Limitations
