* Theoretical Framework
** Systems and System Behaviour
A *system* is formally composed of two major aspects: process and data. In this framework, processes serve as control mechanisms that runs and manipulates data. Meanwhile, data remains static and passively comprises the system [cite:@fokkink2007introduction]. The composition of these elements formsa structure that can perform operations according to specified rules [cite:@plotkin2004structural].
The *behaviour* of a system refers to the sum of its ability to interact or communicate. A behaviour is *observable* because it can be seen from its outside operations; particularly, the interaction of the inputs it accepts and the outputs it produces [cite:@milner1989communication]. Every elementary step or operation that happens in the system is called *transition* that changes the system from its current configuration to another state [cite:@plotkin2004structural].
A *Blockchain* is an example of a system that can be treated as a transaction-based *state machine* [cite:@wood2021ethereum]. In this view, the blockchain is not just a storage of information but a dynamic mechanism where transactions serve as inputs that result to transitions of the distributed ledger's state. Every succesful transaction creates new state that is formally accepted by the whole network. 
The usage of *formal modelling* is critical in this topic in order to give sufficient mathematical evidence for the security and stability of interoperability systems. Formal modelling removes ambiguity and ensures the correctness in comparing asset-bsed and data-based mechanisms under one theoretical framework [cite:@Duan2018] [cite:@fokkink2007introduction].  

