* Theoretical Framework
This section establishes the concepts and theories that supports the investigation of this research. Starting with the foundations of blockchain, proceeding with interoperability and then the chosen formalism method to investigate the semantics of asset and data transfer.

A blockchain is a system from which one can observe certain behaviour. This behaviour or process refers to the totally of the discrete actions that such system executes [cite:@baeten2009process]. Take for example the Bitcoin,
A system behaviour is composed of processes and data [cite:@plotkin2004structural] [cite:@fokkink2007introduction].
Processes are the control mechanisms of data. Processes are active and data are passive [cite:@fokkink2007introduction].

two process terms can be equated if and only if their graphs behaviourally equivalent [cite:@fokkink2007introduction].

System behaviour can be modelled as input output function.

Modelling systems 

Automata theory models process as an automaton. This has a number of states and transitions that connects state to another state. An automaton also has one or more initial states and a number of final states.

When two automaton have the same set of runs called its language, they are semantically equivalent [cite:@baeten2009process].

Transition System is an operation method of specifying semantics  based on syntactic transfromations of programs and simple operations on discrete data [cite:@plotkin2004structural].
By adding an information regarding transitions, transition system becomes a labelled transition system.

Two LTS may be instances of the same process [cite:@vanBenthemBergstra1995].

distributed system.
Main feature is that the global state of a system is composed of a collection of local states [cite:@Gorrieri_2017].




The problem with automata is the notion of interaction that happens in a distributed system.

Operations can be defined to work with processes [cite:@baeten2009process]. 

concurrency theory




